// flow-typed signature: 06b96b4ac05d4838d6e44238a65e5975
// flow-typed version: <<STUB>>/createjs-preloadjs_v^0.6.3/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'createjs-preloadjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'createjs-preloadjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'createjs-preloadjs/_assets/js/examples' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/_assets/libs/easeljs-NEXT.min' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/_assets/libs/soundjs-NEXT.min' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/_assets/libs/tweenjs-NEXT.min' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/_assets/static/alert1' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/_assets/static/scriptExample' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/createjsTheme/assets/js/yui-source' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/Gruntfile' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/path' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/tasks/updatebower' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/tasks/updateversion' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/build/updates/builder' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/lib/preloadjs-0.6.2.combined' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/lib/preloadjs-0.6.2.min' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/lib/preloadjs-NEXT.combined' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/lib/preloadjs-NEXT.min' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/events/ErrorEvent' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/events/Event' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/events/EventDispatcher' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/utils/extend' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/utils/indexOf' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/utils/promote' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/createjs/utils/proxy' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/data/LoadItem' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/data/Methods' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/data/Types' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/events/ProgressEvent' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/AbstractLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/AbstractMediaLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/BinaryLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/CSSLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/ImageLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/JavaScriptLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/JSONLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/JSONPLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/ManifestLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/SoundLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/SpriteSheetLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/SVGLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/TextLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/VideoLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/loaders/XMLLoader' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/LoadQueue' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/net/AbstractRequest' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/net/MediaTagRequest' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/net/TagRequest' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/net/XHRRequest' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/plugins/SamplePlugin' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/DataUtils' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/DomUtils' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/Elements' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/json3' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/RequestUtils' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/utils/URLUtils' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/src/preloadjs/version' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/Gruntfile' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/boot' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/console' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine-html' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/spec/Helpers' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/spec/LoadQueueSpec' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/tasks/findopenport' {
  declare module.exports: any;
}

declare module 'createjs-preloadjs/tests/tasks/listips' {
  declare module.exports: any;
}

// Filename aliases
declare module 'createjs-preloadjs/_assets/js/examples.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/js/examples'>;
}
declare module 'createjs-preloadjs/_assets/libs/easeljs-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/libs/easeljs-NEXT.min'>;
}
declare module 'createjs-preloadjs/_assets/libs/soundjs-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/libs/soundjs-NEXT.min'>;
}
declare module 'createjs-preloadjs/_assets/libs/tweenjs-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/libs/tweenjs-NEXT.min'>;
}
declare module 'createjs-preloadjs/_assets/static/alert1.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/static/alert1'>;
}
declare module 'createjs-preloadjs/_assets/static/scriptExample.js' {
  declare module.exports: $Exports<'createjs-preloadjs/_assets/static/scriptExample'>;
}
declare module 'createjs-preloadjs/build/createjsTheme/assets/js/yui-source.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/createjsTheme/assets/js/yui-source'>;
}
declare module 'createjs-preloadjs/build/Gruntfile.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/Gruntfile'>;
}
declare module 'createjs-preloadjs/build/path.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/path'>;
}
declare module 'createjs-preloadjs/build/tasks/updatebower.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/tasks/updatebower'>;
}
declare module 'createjs-preloadjs/build/tasks/updateversion.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/tasks/updateversion'>;
}
declare module 'createjs-preloadjs/build/updates/builder.js' {
  declare module.exports: $Exports<'createjs-preloadjs/build/updates/builder'>;
}
declare module 'createjs-preloadjs/lib/preloadjs-0.6.2.combined.js' {
  declare module.exports: $Exports<'createjs-preloadjs/lib/preloadjs-0.6.2.combined'>;
}
declare module 'createjs-preloadjs/lib/preloadjs-0.6.2.min.js' {
  declare module.exports: $Exports<'createjs-preloadjs/lib/preloadjs-0.6.2.min'>;
}
declare module 'createjs-preloadjs/lib/preloadjs-NEXT.combined.js' {
  declare module.exports: $Exports<'createjs-preloadjs/lib/preloadjs-NEXT.combined'>;
}
declare module 'createjs-preloadjs/lib/preloadjs-NEXT.min.js' {
  declare module.exports: $Exports<'createjs-preloadjs/lib/preloadjs-NEXT.min'>;
}
declare module 'createjs-preloadjs/src/createjs/events/ErrorEvent.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/events/ErrorEvent'>;
}
declare module 'createjs-preloadjs/src/createjs/events/Event.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/events/Event'>;
}
declare module 'createjs-preloadjs/src/createjs/events/EventDispatcher.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/events/EventDispatcher'>;
}
declare module 'createjs-preloadjs/src/createjs/utils/extend.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/utils/extend'>;
}
declare module 'createjs-preloadjs/src/createjs/utils/indexOf.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/utils/indexOf'>;
}
declare module 'createjs-preloadjs/src/createjs/utils/promote.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/utils/promote'>;
}
declare module 'createjs-preloadjs/src/createjs/utils/proxy.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/createjs/utils/proxy'>;
}
declare module 'createjs-preloadjs/src/preloadjs/data/LoadItem.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/data/LoadItem'>;
}
declare module 'createjs-preloadjs/src/preloadjs/data/Methods.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/data/Methods'>;
}
declare module 'createjs-preloadjs/src/preloadjs/data/Types.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/data/Types'>;
}
declare module 'createjs-preloadjs/src/preloadjs/events/ProgressEvent.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/events/ProgressEvent'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/AbstractLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/AbstractLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/AbstractMediaLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/AbstractMediaLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/BinaryLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/BinaryLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/CSSLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/CSSLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/ImageLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/ImageLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/JavaScriptLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/JavaScriptLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/JSONLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/JSONLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/JSONPLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/JSONPLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/ManifestLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/ManifestLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/SoundLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/SoundLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/SpriteSheetLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/SpriteSheetLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/SVGLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/SVGLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/TextLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/TextLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/VideoLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/VideoLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/loaders/XMLLoader.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/loaders/XMLLoader'>;
}
declare module 'createjs-preloadjs/src/preloadjs/LoadQueue.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/LoadQueue'>;
}
declare module 'createjs-preloadjs/src/preloadjs/net/AbstractRequest.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/net/AbstractRequest'>;
}
declare module 'createjs-preloadjs/src/preloadjs/net/MediaTagRequest.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/net/MediaTagRequest'>;
}
declare module 'createjs-preloadjs/src/preloadjs/net/TagRequest.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/net/TagRequest'>;
}
declare module 'createjs-preloadjs/src/preloadjs/net/XHRRequest.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/net/XHRRequest'>;
}
declare module 'createjs-preloadjs/src/preloadjs/plugins/SamplePlugin.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/plugins/SamplePlugin'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/DataUtils.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/DataUtils'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/DomUtils.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/DomUtils'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/Elements.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/Elements'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/json3.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/json3'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/RequestUtils.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/RequestUtils'>;
}
declare module 'createjs-preloadjs/src/preloadjs/utils/URLUtils.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/utils/URLUtils'>;
}
declare module 'createjs-preloadjs/src/preloadjs/version.js' {
  declare module.exports: $Exports<'createjs-preloadjs/src/preloadjs/version'>;
}
declare module 'createjs-preloadjs/tests/Gruntfile.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/Gruntfile'>;
}
declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/boot.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/lib/jasmine-2.0.2/boot'>;
}
declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/console.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/lib/jasmine-2.0.2/console'>;
}
declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine-html.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine-html'>;
}
declare module 'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/lib/jasmine-2.0.2/jasmine'>;
}
declare module 'createjs-preloadjs/tests/spec/Helpers.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/spec/Helpers'>;
}
declare module 'createjs-preloadjs/tests/spec/LoadQueueSpec.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/spec/LoadQueueSpec'>;
}
declare module 'createjs-preloadjs/tests/tasks/findopenport.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/tasks/findopenport'>;
}
declare module 'createjs-preloadjs/tests/tasks/listips.js' {
  declare module.exports: $Exports<'createjs-preloadjs/tests/tasks/listips'>;
}
