// flow-typed signature: 405535f35418c2a389c41d0296acc7be
// flow-typed version: <<STUB>>/htmlhint-loader_v^1.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlhint-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlhint-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'htmlhint-loader/index' {
  declare module.exports: $Exports<'htmlhint-loader'>;
}
declare module 'htmlhint-loader/index.js' {
  declare module.exports: $Exports<'htmlhint-loader'>;
}
