// flow-typed signature: 6956d1b7855525c3163c5284ea3502d6
// flow-typed version: <<STUB>>/htmlhint_v^0.9.13/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htmlhint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htmlhint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htmlhint/bin/formatter' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/checkstyle' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/compact' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/default' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/json' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/junit' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/markdown' {
  declare module.exports: any;
}

declare module 'htmlhint/bin/formatters/unix' {
  declare module.exports: any;
}

declare module 'htmlhint/Gruntfile' {
  declare module.exports: any;
}

declare module 'htmlhint/lib/htmlhint' {
  declare module.exports: any;
}

declare module 'htmlhint/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htmlhint/bin/formatter.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatter'>;
}
declare module 'htmlhint/bin/formatters/checkstyle.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/checkstyle'>;
}
declare module 'htmlhint/bin/formatters/compact.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/compact'>;
}
declare module 'htmlhint/bin/formatters/default.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/default'>;
}
declare module 'htmlhint/bin/formatters/json.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/json'>;
}
declare module 'htmlhint/bin/formatters/junit.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/junit'>;
}
declare module 'htmlhint/bin/formatters/markdown.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/markdown'>;
}
declare module 'htmlhint/bin/formatters/unix.js' {
  declare module.exports: $Exports<'htmlhint/bin/formatters/unix'>;
}
declare module 'htmlhint/Gruntfile.js' {
  declare module.exports: $Exports<'htmlhint/Gruntfile'>;
}
declare module 'htmlhint/index' {
  declare module.exports: $Exports<'htmlhint'>;
}
declare module 'htmlhint/index.js' {
  declare module.exports: $Exports<'htmlhint'>;
}
declare module 'htmlhint/lib/htmlhint.js' {
  declare module.exports: $Exports<'htmlhint/lib/htmlhint'>;
}
declare module 'htmlhint/test.js' {
  declare module.exports: $Exports<'htmlhint/test'>;
}
