// flow-typed signature: a73f457bbb67082610447f5cec440b1a
// flow-typed version: <<STUB>>/stylelint-csstree-validator_v^1.1.1/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-csstree-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-csstree-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-csstree-validator/syntax-extension/index' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/syntax-extension/less/LessEscaping' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/syntax-extension/less/LessVariable' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/syntax-extension/less/LessVariableReference' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/syntax-extension/sass/SassInterpolation' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/syntax-extension/sass/SassVariable' {
  declare module.exports: any;
}

declare module 'stylelint-csstree-validator/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-csstree-validator/index' {
  declare module.exports: $Exports<'stylelint-csstree-validator'>;
}
declare module 'stylelint-csstree-validator/index.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/index.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/index'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/less/LessEscaping.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/less/LessEscaping'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/less/LessVariable.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/less/LessVariable'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/less/LessVariableReference.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/less/LessVariableReference'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/sass/SassInterpolation.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/sass/SassInterpolation'>;
}
declare module 'stylelint-csstree-validator/syntax-extension/sass/SassVariable.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/syntax-extension/sass/SassVariable'>;
}
declare module 'stylelint-csstree-validator/test/index.js' {
  declare module.exports: $Exports<'stylelint-csstree-validator/test/index'>;
}
